
source:
    type: prometheus
    url: localhost
    port: 9090
    metric: /dummmy
job: 
    type: regression
    order: 2
workers:
    type: RQ
    n_workers: 1
sink:
    type: internal
output:
    carry: True


